"""
initialize constants which are going to use
"""
property_file = "config\knapsack.properties"
regex_pattern_english_alphabet = "[a-zA-Z]+$"
regex_pattern_digit = "\d+$"
regex_pattern_range = "\d+-\d+$"
regex_pattern_boolean = "(?i)true$|false$"
regex_pattern_decipher_side_choice = "(?i)^(r|a)$"
terminal_delimiter = "\n*******************"
section_vector = "VectorSection"
section_parameters = "ParametersSection"
algorithm_brute_force = "BruteForce"
algorithm_totient = "Totient"
algorithm_back_tracking = "BackTracking"
structure_type_string = "String"
structure_type_boolean = "Boolean"
structure_type_int = "Int"
structure_type_float = "Float"
